include: package:flutter_lints/flutter.yaml

linter:
  # https://dart-lang.github.io/linter/lints/index.html.
  rules:
    always_require_non_null_named_parameters: true
    avoid_empty_else: true
    avoid_function_literals_in_foreach_calls: true # Removable
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_print: true
    avoid_renaming_method_parameters: true
    avoid_return_types_on_setters: true
    avoid_returning_null_for_void: true
    avoid_shadowing_type_parameters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_types_as_parameter_names: true
    await_only_futures: true
    camel_case_extensions: true
    camel_case_types: true
    constant_identifier_names: true
    curly_braces_in_flow_control_structures: true
    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true
    file_names: true
    implementation_imports: true
    library_names: true
    library_prefixes: true
    no_duplicate_case_values: true
    non_constant_identifier_names: true
    null_closures: true
    omit_local_variable_types: true
    overridden_fields: true
    prefer_single_quotes: true
    prefer_void_to_null: true
    unrelated_type_equality_checks: true
    valid_regexps: true
    package_prefixed_library_names: true
    prefer_adjacent_string_concatenation: true
    hash_and_equals: true # Removable
    prefer_conditional_assignment: true
    prefer_contains: true
    prefer_equal_for_default_values: true
    prefer_final_fields: true
    prefer_for_elements_to_map_fromIterable: true # Removable
    prefer_function_declarations_over_variables: true
    prefer_generic_function_type_aliases: true # Removable
    prefer_if_null_operators: true
    prefer_initializing_formals: true # Removable
    prefer_inlined_adds: true # Removable
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_null_aware_operators: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    provide_deprecation_message: true
    recursive_getters: true
    slash_for_doc_comments: true
    type_init_formals: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true # Removable
    unnecessary_new: true
    unnecessary_getters_setters: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_overrides: true # Removable
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    use_full_hex_values_for_flutter_colors: true
    use_function_type_syntax_for_parameters: true # Removable
    use_rethrow_when_possible: true # Removable
    void_checks: true # Removable
    package_names: true